### ISSUE TITLE
PublicHolidaysLawYearの扱いについって

### ISSUE THREAD

**Issue by akuraru** [fumiyasac/handMadeCalendarAdvance#10]
1948年以前はにも祝祭日であった春分の日祝日判定されないのはどのような意図があるのでしょうか？
https://ja.wikipedia.org/wiki/%E7%9A%87%E9%9C%8A%E7%A5%AD

**Comment by fumiyasac** [comment]
ありがとうございます！確認します。（単純に抜けですね。。厳密にするなら書かないといけないですね）
春分・秋分は現状テストケースが2000年~2030年までなので、2000年以前のデータも探してみます。

**Comment by akuraru** [comment]
Wikipadiaにあった

春分
https://ja.wikipedia.org/wiki/%E6%98%A5%E5%88%86
秋分
https://ja.wikipedia.org/wiki/%E7%A7%8B%E5%88%86

**Comment by fumiyasac** [comment]
こちらの方は今回のカレンダーでは1948年以降を基準とするため、今回は対応を一旦見送ります。
