### ISSUE TITLE
振替休日の制定

### ISSUE THREAD

**Issue by akuraru** [fumiyasac/handMadeCalendarAdvance#11]
振替休日は1973年以降にしかないので、変更する
https://ja.wikipedia.org/wiki/%E6%8C%AF%E6%9B%BF%E4%BC%91%E6%97%A5#.E5.A4.89.E9.81.B7

**Comment by fumiyasac** [comment]
これは考慮しないといけないやつですね。。。こちらもすみませんです。

**Comment by akuraru** [comment]
方針としてカバーする年数が明確ならからなくていいと思います

**Comment by fumiyasac** [comment]
こちらは月曜までに決めようと思います。
※[PublicHolidaysLawYearの扱いについて #10](https://github.com/fumiyasac/handMadeCalendarAdvance/issues/10)についても同様にこのissueと合わせて実装 or 非実装を決定。

**Comment by fumiyasac** [comment]
下記タスクは優先度（低）としていったんはPendingしようと思います。
・振替休日の制定 #11
・PublicHolidaysLawYearの扱いについて #10 
和暦でテストが落ちる件の解決のほうを優先して進めていく予定です。

**Comment by fumiyasac** [comment]
こちらfeature/swift3ブランチの方に対応しました。
★ブランチ：
https://github.com/fumiyasac/handMadeCalendarAdvance/tree/feature/swift3
★コミットログ：
https://github.com/fumiyasac/handMadeCalendarAdvance/commit/ed12e6d030f3bcbfbb1c83805ec9c7708b6cf829
