### ISSUE TITLE
天皇陛下退位に伴う祝日の変更の可能性

### ISSUE THREAD

**Issue by akuraru** [fumiyasac/handMadeCalendarAdvance#19]
西暦2018年3月31日に天皇陛下が退位なされることに伴って、天皇誕生日が別の日になると予想される。現在未定。

**Comment by fumiyasac** [comment]
ありがとうございます！注意して動向確認するように致しますm(_ _)m

**Comment by akuraru** [comment]
`(未施行の規定を含む)`となっていますが、西暦2019年以降の12/23天皇誕生日はない模様。
http://www8.cao.go.jp/chosei/shukujitsu/gaiyou.html#syukujitu

**Comment by akuraru** [comment]
西暦2019年5月1日は、臨時の休日になる可能性がある。
https://mainichi.jp/articles/20171206/k00/00e/010/292000c

**Comment by fumiyasac** [comment]
@akuraru 情報ありがとうございます！直近のニュースも含めて確認してみます。

**Comment by fumiyasac** [comment]
こちらのプルリクエストで対応しました。
https://github.com/fumiyasac/handMadeCalendarAdvance/pull/24
