### ISSUE TITLE
端末の設定が和暦だと正しく祝日判定がされない

### ISSUE THREAD

**Issue by sukkuuuuu** [fumiyasac/handMadeCalendarAdvance#22]
ライブラリの作成ありがとうございます！使わせて頂いた中で気付いたことがありましたので、
対応していただけると助かります。

実機端末の設定を和暦にした状態だと、祝日であるべき日が祝日だと判定されてないように思います。

https://github.com/fumiyasac/handMadeCalendarAdvance/issues/12
過去に同じようなissueが上がって対応されたようですが、現在のMasterだと反映されていないのかなと。

`let cal = Calendar.current as NSCalendar`

これで初期化してる箇所を
`let cal = Calendar(identifier: .gregorian)`

で初期化した方が良いのではないでしょうか？

ご確認よろしくお願い致します。

**Comment by fumiyasac** [comment]
遅くなり申し訳ありませんでした...ありがとうございます！
この部分は書き直しの際にもれてしまった部分ですね...できるだけ早めに対応致します。

**Comment by fumiyasac** [comment]
頂きましたPullRequestをmergeした上で、アプリバージョンを`0.1.7`へアップデートしました。
ご指摘を頂きましてありがとうございました。
