### ISSUE TITLE
CocoaPodsのバージョンが上げられない問題

### ISSUE THREAD

**Issue by fumiyasac** [fumiyasac/handMadeCalendarAdvance#26]
### 発生している問題

下記のコマンドを実行して.podspecファイルの更新を行なった際に下記のようなエラーが出てしまいバージョンアップができない状態になっている。解決方法がわかっていない。

#### 実行したコマンド

`$ pod spec lint --verbose CalculateCalendarLogic.podspec`

#### 行なった対応

Xcode10系＆Swift4.2用のバージョンアップを実行した。

__該当のPullRequest:__

https://github.com/fumiyasac/handMadeCalendarAdvance/pull/25

#### 出力されたエラーログ

何度やっても下記のようなログが出て失敗する。

```
$ pod trunk push CalculateCalendarLogic.podspec
Updating spec repo `master`

CocoaPods 1.6.0.beta.2 is available.
To update use: `sudo gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.6.0.beta.2

Validating podspec
 -> CalculateCalendarLogic (0.2.1)
    - NOTE  | xcodebuild:  note: Using new build system
    - NOTE  | xcodebuild:  note: Planning build
    - NOTE  | xcodebuild:  note: Constructing build description
    - NOTE  | [iOS] xcodebuild:  warning: Skipping code signing because the target does not have an Info.plist file. (in target 'App')
    - ERROR | [OSX] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.

[!] The spec did not pass validation, due to 1 error.
```

**Comment by DaisukeNagata** [comment]
‪自分もSwift4.2の時に一度発生しました。‬

‪様々に試した中で解決されませんでした。‬

‪根本的な解決ではないですが、tagのバージョンを変更して、再度trunk pushしたら、いつも通りの対応で出来ました。‬

**Comment by fumiyasac** [comment]
@daisukenagata ありがとうございます。再度タグのバージョン等を変更してみましたが、そもそもlintが通っていない & Xcodeでビルドできていない感じだったので、OSXのフレームワーク側の設定を見直す必要がありそうです。

### 実行コマンド

`$pod spec lint CalculateCalendarLogic.podspec --verbose --allow-warnings`

**Comment by DaisukeNagata** [comment]
@fumiyasac
了解しました。Xcode preferencesのXcodeバージョン設定も最新になっていればbuild出来たとは思いましたが、症状としては直りそうですね。ライブラリー楽しみにしてます。

**Comment by fumiyasac** [comment]
### 解決方法

下記のように対応を行うことで一旦は実行ができることを確認（というよりも1.6.0.beta.2をこのリポジトリでは使用する対応が正しいと思われます）

__OSX対応部分での修正:__

+ Swiftのバージョンが4.0のままだったので、4.2へ変更しました。

__Gemfileを追加してこのリポジトリでのCocoaPodsのバージョンを指定する:__

```
# frozen_string_literal: true
source "https://rubygems.org"
gem 'cocoapods', '1.6.0.beta.2'
# gem "rails"
```

__下記のコマンドを実行して、チェックが通ること＆アップロードができたことを確認する:__

```
【確認】
$ bundle exec pod spec lint CalculateCalendarLogic.podspec --verbose --allow-warnings
【アップロード】
$ bundle exec pod trunk push CalculateCalendarLogic.podspec
```
