### ISSUE TITLE
LICENSEファイルの追加

### ISSUE THREAD

**Issue by akio0911** [fumiyasac/handMadeCalendarAdvance#3]
The MIT License (MIT)のファイルなどを追加すれば、ライセンスの内容が明確になるので利用しやすくなるかなと思いました。

See also: https://github.com/akio0911/MaxWidthConstraints/blob/master/LICENSE

**Comment by fumiyasac** [comment]
ライセンス表記ありがとうございます。
こちらもREADMEに追記致しますm(_ _)m

**Comment by fumiyasac** [comment]
ライセンスファイルも追加頂きましてありがとうございますm(_ _)m
こちらのissueはクローズ致します。
